version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: kiotviet_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "33006:3306" # Host port 33006 â†’ container port 3306
    command: >
      --default-authentication-plugin=mysql_native_password
