services:
  mysql:
    image: "mysql:8.0"
    environment:
      - "MYSQL_DATABASE=kiotviet_db"
      - "MYSQL_PASSWORD=user1234"
      - "MYSQL_ROOT_PASSWORD=root1234"
      - "MYSQL_USER=user"
    ports:
      - "33006:3306"
